# Generated by Django 5.0 on 2023-12-11 09:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendorperformance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
